development:
  sessions:
    default:
      database: operation-flow-editor_dev1
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: operation-flow-editor_test
      hosts:
        - localhost:27017